###
# Handles application dependencies and environment variables
# Also syncs the application with the database schema
##
- name: create virtualenv directory if it does not already exist
  file: path={{ venv_dir }} state=directory

- name: install dependencies into a new virtualenv
  pip: requirements={{ api_dir }}/requirements.txt
       virtualenv={{ venv_dir }}

- name: create .env file in base directory of the app from template
  template: src=env.j2
            dest={{ app_dir }}/.env

- name: create data migrations if necessary 
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ api_dir }}/manage.py makemigrations --noinput"

- name: apply migrations on PostgreSQL via Django
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ api_dir }}/manage.py migrate --noinput"

